# Jekyll
permalink: /:year/:title/
paginate: 10
exclude: []
name: WeichenXu123
baseurl: /MyBlog
mysitetitle: "Weichen Xu's Tech Blog"
myemail: "WeichenXu123 at outlook.com"
aboutmelink: "/2011/introducing-jekyll-bootstrap/"
highlight: true
highlighter: pygments
